/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author Priwidy
 */
public class Dosen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dosen.class.getName());

    /**
     * Creates new form Mahasiswa
     */
    public Dosen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        LogoSiasat = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Nova = new javax.swing.JLabel();
        Semester1 = new javax.swing.JLabel();
        BebanSks = new javax.swing.JLabel();
        PanelBio = new javax.swing.JPanel();
        HomeIcon = new javax.swing.JLabel();
        TextHome = new javax.swing.JLabel();
        SelamatDatang = new javax.swing.JLabel();
        SelamatDatangPortal = new javax.swing.JLabel();
        DataMahasiswa = new javax.swing.JLabel();
        IconDosenPanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Biodata = new javax.swing.JLabel();
        TanggalLahir = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Umur = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        TanggalLahir2 = new javax.swing.JLabel();
        RiwayatPendidikan = new javax.swing.JLabel();
        AngkaUmur = new javax.swing.JLabel();
        DikyPrastyo = new javax.swing.JLabel();
        JalanKemiri = new javax.swing.JLabel();
        S1 = new javax.swing.JLabel();
        S2 = new javax.swing.JLabel();
        S1SI = new javax.swing.JLabel();
        EmailDiky = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        Jadwal = new javax.swing.JButton();
        Registrasi = new javax.swing.JButton();
        KartuStudi3 = new javax.swing.JButton();
        Log_out = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setBackground(new java.awt.Color(255, 255, 255));

        LogoSiasat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LogoSiasat.setForeground(new java.awt.Color(255, 255, 255));
        LogoSiasat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/Icon (1).gif"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Nova.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nova.setForeground(new java.awt.Color(255, 153, 0));
        Nova.setText(": : DICKY PRASTYO M.KOM (FAKULTAS TEKNOLOGI INFORMASI - TEKNIK INFORMATIKA)   ");

        Semester1.setForeground(new java.awt.Color(255, 153, 0));
        Semester1.setText(": : SEMESTER 1 TA 2025 - 2026");

        BebanSks.setForeground(new java.awt.Color(255, 153, 0));
        BebanSks.setText(": : BEBAN SKS MAKSIMAL : - SKS");

        PanelBio.setBackground(new java.awt.Color(255, 255, 255));

        HomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/Home.jpg"))); // NOI18N

        TextHome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextHome.setForeground(new java.awt.Color(0, 0, 0));
        TextHome.setText("HOME");

        SelamatDatang.setBackground(new java.awt.Color(255, 255, 255));
        SelamatDatang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SelamatDatang.setForeground(new java.awt.Color(0, 0, 0));
        SelamatDatang.setText("SELAMAT DATANG DI SISTEM INFORMASI AKADEMIK SATYA WACANA ");

        SelamatDatangPortal.setBackground(new java.awt.Color(255, 255, 255));
        SelamatDatangPortal.setForeground(new java.awt.Color(0, 0, 0));
        SelamatDatangPortal.setText("SELAMAT DATANG DI PORTAL SISTEM INFORMASI AKADEMIK DOSEN, TEMPAT DI MANA ANDA DAPAT MENGAKSES BERBAGAI FITUR PENGELOLAAN PERKULIAHAN");

        DataMahasiswa.setBackground(new java.awt.Color(255, 255, 255));
        DataMahasiswa.setForeground(new java.awt.Color(0, 0, 0));
        DataMahasiswa.setText("DATA MAHASISWA, JADWAL MENGAJAR, SERTA PROSES ADMINISTRASI AKADEMIK DENGAN MUDAH DAN CEPAT.");

        IconDosenPanel.setBackground(new java.awt.Color(255, 255, 255));
        IconDosenPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/IconDosen.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(java.awt.Color.white);

        Biodata.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Biodata.setForeground(new java.awt.Color(255, 255, 255));
        Biodata.setText("BIODATA DOSEN");

        TanggalLahir.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        TanggalLahir.setForeground(java.awt.Color.white);
        TanggalLahir.setText("21 Desember 1980");

        Nama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Nama.setForeground(new java.awt.Color(255, 255, 255));
        Nama.setText("NAMA                                 :");

        Umur.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Umur.setForeground(new java.awt.Color(255, 255, 255));
        Umur.setText("UMUR                                :");

        Alamat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Alamat.setForeground(new java.awt.Color(255, 255, 255));
        Alamat.setText("ALAMAT                            :");

        Email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("EMAIL                                  :");

        TanggalLahir2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TanggalLahir2.setForeground(new java.awt.Color(255, 255, 255));
        TanggalLahir2.setText("TANGGAL LAHIR             :");

        RiwayatPendidikan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RiwayatPendidikan.setForeground(new java.awt.Color(255, 255, 255));
        RiwayatPendidikan.setText("RIWAYAT PENDIDIKAN :");

        AngkaUmur.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        AngkaUmur.setForeground(java.awt.Color.white);
        AngkaUmur.setText("20");

        DikyPrastyo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        DikyPrastyo.setForeground(java.awt.Color.white);
        DikyPrastyo.setText("Diky Prastyo M.Kom");

        JalanKemiri.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JalanKemiri.setForeground(java.awt.Color.white);
        JalanKemiri.setText("Jl. Kemiri No. 39");

        S1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        S1.setForeground(java.awt.Color.white);
        S1.setText("- S1 (Sarjana) – Sistem Informasi, Universitas Diponegoro, 2009 ");

        S2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        S2.setForeground(java.awt.Color.white);
        S2.setText("- S2 (Magister) – Teknik Informatika, Institut Teknologi Bandung, 2013");

        S1SI.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        S1SI.setForeground(java.awt.Color.white);
        S1SI.setText("- S1 (Sarjana) – Sistem Informasi, Universitas Diponegoro, 2009");

        EmailDiky.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        EmailDiky.setForeground(java.awt.Color.white);
        EmailDiky.setText("dikyprastyo@gmail.com");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Biodata)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S2)
                            .addComponent(S1)
                            .addComponent(S1SI)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmailDiky))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Alamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TanggalLahir2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Umur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RiwayatPendidikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TanggalLahir)
                            .addComponent(AngkaUmur)
                            .addComponent(JalanKemiri)
                            .addComponent(DikyPrastyo))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Biodata)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(DikyPrastyo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Umur)
                    .addComponent(AngkaUmur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TanggalLahir2)
                    .addComponent(TanggalLahir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alamat)
                    .addComponent(JalanKemiri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RiwayatPendidikan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S1SI)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(EmailDiky))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelBioLayout = new javax.swing.GroupLayout(PanelBio);
        PanelBio.setLayout(PanelBioLayout);
        PanelBioLayout.setHorizontalGroup(
            PanelBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBioLayout.createSequentialGroup()
                .addGroup(PanelBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBioLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(PanelBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelamatDatang)
                            .addGroup(PanelBioLayout.createSequentialGroup()
                                .addComponent(HomeIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextHome))))
                    .addGroup(PanelBioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SelamatDatangPortal))
                    .addGroup(PanelBioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DataMahasiswa))
                    .addGroup(PanelBioLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(IconDosenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(288, 288, 288))
        );
        PanelBioLayout.setVerticalGroup(
            PanelBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBioLayout.createSequentialGroup()
                .addGroup(PanelBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HomeIcon)
                    .addComponent(TextHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelamatDatang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SelamatDatangPortal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DataMahasiswa)
                .addGap(85, 85, 85)
                .addGroup(PanelBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IconDosenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        PanelMenu.setBackground(new java.awt.Color(51, 51, 51));
        PanelMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelMenu.setForeground(new java.awt.Color(0, 0, 0));

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Jadwal.setText("Input Nilai");
        Jadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JadwalActionPerformed(evt);
            }
        });

        Registrasi.setText("Jadwal Mengajar");
        Registrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrasiActionPerformed(evt);
            }
        });

        KartuStudi3.setText("Lupa Password");
        KartuStudi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KartuStudi3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(KartuStudi3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Registrasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(Home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Registrasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jadwal)
                .addGap(123, 123, 123)
                .addComponent(KartuStudi3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Log_out.setBackground(new java.awt.Color(255, 0, 0));
        Log_out.setForeground(new java.awt.Color(255, 255, 255));
        Log_out.setText("Logout");
        Log_out.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 1, true));
        Log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_outActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nova)
                            .addComponent(Semester1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(712, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BebanSks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelBio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Nova)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Semester1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BebanSks)
                    .addComponent(Log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelBio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoSiasat)
                .addContainerGap())
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LogoSiasat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        new Dosen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void Log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_outActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Log_outActionPerformed

    private void JadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JadwalActionPerformed
        // TODO add your handling code here:
        new InputNilai().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JadwalActionPerformed

    private void KartuStudi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KartuStudi3ActionPerformed
        // TODO add your handling code here:
         new LupaPasswordAdmin().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_KartuStudi3ActionPerformed

    private void RegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrasiActionPerformed
        // TODO add your handling code here:
        new JadwalMengajar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegistrasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dosen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel AngkaUmur;
    private javax.swing.JLabel BebanSks;
    private javax.swing.JLabel Biodata;
    private javax.swing.JLabel DataMahasiswa;
    private javax.swing.JLabel DikyPrastyo;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel EmailDiky;
    private javax.swing.JButton Home;
    private javax.swing.JLabel HomeIcon;
    private javax.swing.JLabel IconDosenPanel;
    private javax.swing.JButton Jadwal;
    private javax.swing.JLabel JalanKemiri;
    private javax.swing.JButton KartuStudi3;
    private javax.swing.JButton Log_out;
    private javax.swing.JLabel LogoSiasat;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Nova;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel PanelBio;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JButton Registrasi;
    private javax.swing.JLabel RiwayatPendidikan;
    private javax.swing.JLabel S1;
    private javax.swing.JLabel S1SI;
    private javax.swing.JLabel S2;
    private javax.swing.JLabel SelamatDatang;
    private javax.swing.JLabel SelamatDatangPortal;
    private javax.swing.JLabel Semester1;
    private javax.swing.JLabel TanggalLahir;
    private javax.swing.JLabel TanggalLahir2;
    private javax.swing.JLabel TextHome;
    private javax.swing.JLabel Umur;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
